export const FiltersTypes = {
  SET_SORT_BY: 'SET_SORT_BY',
  SET_ACTIVE_CATEGORY: 'SET_ACTIVE_CATEGORY',
};

export const ProductsTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_LOADING: 'SET_LOADING',
};

export const CartTypes = {
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  CLEAR_CART: 'CLEAR_CART',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  PLUS_ITEM: 'PLUS_ITEM',
  MINUS_ITEM: 'MINUS_ITEM',
};
